"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import Sidebar from "./components/sidebar";
import Searchbar from "./components/searchbar";

import { Provider } from "react-redux";
import { store } from "./redux/store";

import SignInModal from "./components/signIn";
import { initFirebase } from "./firebase";
import { getAuth } from "firebase/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const app = initFirebase();
  const auth = getAuth(app);

  const pathName = usePathname();
  const isHomePage = pathName === "/";
  const isPlanPage = pathName === "/choose-plan";

  return (
    <html lang="en">
      <Provider store={store}>
        {isHomePage || isPlanPage ? (
          <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <SignInModal />
            {children}
          </body>
        ) : (
          <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <SignInModal />
            <Searchbar />
            <Sidebar />
            {children}
          </body>
        )}
      </Provider>
    </html>
  );
}
