import HomePage from "./components/homePage";

export const metadata = {
  title: "Summarist",
  description: "Generated by create next app",
};

export default function Home() {
  return <HomePage />;
}
